# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.java.home=C:/Users/anoop/.jdks/temurin-21.0.12
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Common Mod Properties
mod_id=zap_hosting_server_integration_menu
mod_name=Zap-Hosting Menu
mod_license=All Rights Reserved
mod_version=1.101.2
mod_group_id=com.reggarf.mods
mod_authors=Reggarf
mod_description=A ZAP-Hosting Server Integration Menu For Modpack

## 26.1 Properties
minecraft_version_26=26.1.2
minecraft_version_26_forge=26.1
minecraft_version_range_26=[26.1,)
java_version_26=25
neo_version_26=26.1.2.71
neo_version_range_26=[26,)
forge_version_26=62.0.9
fabric_loader_version_26=0.18.5
fabric_api_version_26=0.155.3+26.1.2

## 1.21.1 Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.0,)
java_version=21
neo_version=21.1.252
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

fabric_loader_version_1_21=0.16.9
fabric_api_version_1_21=0.102.1+1.21.1
modmenu_version_1_21=11.0.3
forge_version_1_21=52.1.0

## 1.20.1 Forge & Fabric Properties
minecraft_version_1_20=1.20.1
java_version_1_20=17
forge_version_1_20=47.3.0
fabric_loader_version_1_20=0.15.11
fabric_api_version_1_20=0.92.2+1.20.1
